/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as HealthRouteImport } from './routes/health'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CountryCodeRouteImport } from './routes/$countryCode'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountryCodeIndexRouteImport } from './routes/$countryCode/index'
import { Route as CountryCodeVirtualTryOnRouteImport } from './routes/$countryCode/virtual-try-on'
import { Route as CountryCodeTermsRouteImport } from './routes/$countryCode/terms'
import { Route as CountryCodeStoreRouteImport } from './routes/$countryCode/store'
import { Route as CountryCodeShippingPolicyRouteImport } from './routes/$countryCode/shipping-policy'
import { Route as CountryCodeSearchRouteImport } from './routes/$countryCode/search'
import { Route as CountryCodeReturnPolicyRouteImport } from './routes/$countryCode/return-policy'
import { Route as CountryCodePrivacyPolicyRouteImport } from './routes/$countryCode/privacy-policy'
import { Route as CountryCodePhoneVerifyRouteImport } from './routes/$countryCode/phone-verify'
import { Route as CountryCodeFaqsRouteImport } from './routes/$countryCode/faqs'
import { Route as CountryCodeContactRouteImport } from './routes/$countryCode/contact'
import { Route as CountryCodeCheckoutRouteImport } from './routes/$countryCode/checkout'
import { Route as CountryCodeCartRouteImport } from './routes/$countryCode/cart'
import { Route as CountryCodeAccountRouteImport } from './routes/$countryCode/account'
import { Route as CountryCodeAboutRouteImport } from './routes/$countryCode/about'
import { Route as CountryCodeBlogsIndexRouteImport } from './routes/$countryCode/blogs/index'
import { Route as CountryCodeProductsHandleRouteImport } from './routes/$countryCode/products/$handle'
import { Route as CountryCodeCategoriesHandleRouteImport } from './routes/$countryCode/categories/$handle'
import { Route as CountryCodeBlogsSlugRouteImport } from './routes/$countryCode/blogs/$slug'
import { Route as CountryCodeAccountRegisterRouteImport } from './routes/$countryCode/account/register'
import { Route as CountryCodeAccountProfileRouteImport } from './routes/$countryCode/account/profile'
import { Route as CountryCodeAccountPasswordLoginRouteImport } from './routes/$countryCode/account/password-login'
import { Route as CountryCodeAccountOrdersRouteImport } from './routes/$countryCode/account/orders'
import { Route as CountryCodeAccountLoginRouteImport } from './routes/$countryCode/account/login'
import { Route as CountryCodeAccountAddressesRouteImport } from './routes/$countryCode/account/addresses'
import { Route as CountryCodeOrderOrderIdConfirmedRouteImport } from './routes/$countryCode/order/$orderId/confirmed'
import { Route as CountryCodeAccountOrdersOrderIdRouteImport } from './routes/$countryCode/account/orders_.$orderId'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeRoute = CountryCodeRouteImport.update({
  id: '/$countryCode',
  path: '/$countryCode',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeIndexRoute = CountryCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeVirtualTryOnRoute = CountryCodeVirtualTryOnRouteImport.update({
  id: '/virtual-try-on',
  path: '/virtual-try-on',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeTermsRoute = CountryCodeTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeStoreRoute = CountryCodeStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeShippingPolicyRoute =
  CountryCodeShippingPolicyRouteImport.update({
    id: '/shipping-policy',
    path: '/shipping-policy',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeSearchRoute = CountryCodeSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeReturnPolicyRoute = CountryCodeReturnPolicyRouteImport.update({
  id: '/return-policy',
  path: '/return-policy',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodePrivacyPolicyRoute =
  CountryCodePrivacyPolicyRouteImport.update({
    id: '/privacy-policy',
    path: '/privacy-policy',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodePhoneVerifyRoute = CountryCodePhoneVerifyRouteImport.update({
  id: '/phone-verify',
  path: '/phone-verify',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeFaqsRoute = CountryCodeFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeContactRoute = CountryCodeContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeCheckoutRoute = CountryCodeCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeCartRoute = CountryCodeCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeAccountRoute = CountryCodeAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeAboutRoute = CountryCodeAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeBlogsIndexRoute = CountryCodeBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeProductsHandleRoute =
  CountryCodeProductsHandleRouteImport.update({
    id: '/products/$handle',
    path: '/products/$handle',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeCategoriesHandleRoute =
  CountryCodeCategoriesHandleRouteImport.update({
    id: '/categories/$handle',
    path: '/categories/$handle',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeBlogsSlugRoute = CountryCodeBlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeAccountRegisterRoute =
  CountryCodeAccountRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => CountryCodeAccountRoute,
  } as any)
const CountryCodeAccountProfileRoute =
  CountryCodeAccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => CountryCodeAccountRoute,
  } as any)
const CountryCodeAccountPasswordLoginRoute =
  CountryCodeAccountPasswordLoginRouteImport.update({
    id: '/password-login',
    path: '/password-login',
    getParentRoute: () => CountryCodeAccountRoute,
  } as any)
const CountryCodeAccountOrdersRoute =
  CountryCodeAccountOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => CountryCodeAccountRoute,
  } as any)
const CountryCodeAccountLoginRoute = CountryCodeAccountLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CountryCodeAccountRoute,
} as any)
const CountryCodeAccountAddressesRoute =
  CountryCodeAccountAddressesRouteImport.update({
    id: '/addresses',
    path: '/addresses',
    getParentRoute: () => CountryCodeAccountRoute,
  } as any)
const CountryCodeOrderOrderIdConfirmedRoute =
  CountryCodeOrderOrderIdConfirmedRouteImport.update({
    id: '/order/$orderId/confirmed',
    path: '/order/$orderId/confirmed',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountOrdersOrderIdRoute =
  CountryCodeAccountOrdersOrderIdRouteImport.update({
    id: '/orders_/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => CountryCodeAccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$countryCode': typeof CountryCodeRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/health': typeof HealthRoute
  '/store': typeof StoreRoute
  '/$countryCode/about': typeof CountryCodeAboutRoute
  '/$countryCode/account': typeof CountryCodeAccountRouteWithChildren
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/contact': typeof CountryCodeContactRoute
  '/$countryCode/faqs': typeof CountryCodeFaqsRoute
  '/$countryCode/phone-verify': typeof CountryCodePhoneVerifyRoute
  '/$countryCode/privacy-policy': typeof CountryCodePrivacyPolicyRoute
  '/$countryCode/return-policy': typeof CountryCodeReturnPolicyRoute
  '/$countryCode/search': typeof CountryCodeSearchRoute
  '/$countryCode/shipping-policy': typeof CountryCodeShippingPolicyRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode/terms': typeof CountryCodeTermsRoute
  '/$countryCode/virtual-try-on': typeof CountryCodeVirtualTryOnRoute
  '/$countryCode/': typeof CountryCodeIndexRoute
  '/$countryCode/account/addresses': typeof CountryCodeAccountAddressesRoute
  '/$countryCode/account/login': typeof CountryCodeAccountLoginRoute
  '/$countryCode/account/orders': typeof CountryCodeAccountOrdersRoute
  '/$countryCode/account/password-login': typeof CountryCodeAccountPasswordLoginRoute
  '/$countryCode/account/profile': typeof CountryCodeAccountProfileRoute
  '/$countryCode/account/register': typeof CountryCodeAccountRegisterRoute
  '/$countryCode/blogs/$slug': typeof CountryCodeBlogsSlugRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/blogs/': typeof CountryCodeBlogsIndexRoute
  '/$countryCode/account/orders/$orderId': typeof CountryCodeAccountOrdersOrderIdRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/health': typeof HealthRoute
  '/store': typeof StoreRoute
  '/$countryCode/about': typeof CountryCodeAboutRoute
  '/$countryCode/account': typeof CountryCodeAccountRouteWithChildren
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/contact': typeof CountryCodeContactRoute
  '/$countryCode/faqs': typeof CountryCodeFaqsRoute
  '/$countryCode/phone-verify': typeof CountryCodePhoneVerifyRoute
  '/$countryCode/privacy-policy': typeof CountryCodePrivacyPolicyRoute
  '/$countryCode/return-policy': typeof CountryCodeReturnPolicyRoute
  '/$countryCode/search': typeof CountryCodeSearchRoute
  '/$countryCode/shipping-policy': typeof CountryCodeShippingPolicyRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode/terms': typeof CountryCodeTermsRoute
  '/$countryCode/virtual-try-on': typeof CountryCodeVirtualTryOnRoute
  '/$countryCode': typeof CountryCodeIndexRoute
  '/$countryCode/account/addresses': typeof CountryCodeAccountAddressesRoute
  '/$countryCode/account/login': typeof CountryCodeAccountLoginRoute
  '/$countryCode/account/orders': typeof CountryCodeAccountOrdersRoute
  '/$countryCode/account/password-login': typeof CountryCodeAccountPasswordLoginRoute
  '/$countryCode/account/profile': typeof CountryCodeAccountProfileRoute
  '/$countryCode/account/register': typeof CountryCodeAccountRegisterRoute
  '/$countryCode/blogs/$slug': typeof CountryCodeBlogsSlugRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/blogs': typeof CountryCodeBlogsIndexRoute
  '/$countryCode/account/orders/$orderId': typeof CountryCodeAccountOrdersOrderIdRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$countryCode': typeof CountryCodeRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/health': typeof HealthRoute
  '/store': typeof StoreRoute
  '/$countryCode/about': typeof CountryCodeAboutRoute
  '/$countryCode/account': typeof CountryCodeAccountRouteWithChildren
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/contact': typeof CountryCodeContactRoute
  '/$countryCode/faqs': typeof CountryCodeFaqsRoute
  '/$countryCode/phone-verify': typeof CountryCodePhoneVerifyRoute
  '/$countryCode/privacy-policy': typeof CountryCodePrivacyPolicyRoute
  '/$countryCode/return-policy': typeof CountryCodeReturnPolicyRoute
  '/$countryCode/search': typeof CountryCodeSearchRoute
  '/$countryCode/shipping-policy': typeof CountryCodeShippingPolicyRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode/terms': typeof CountryCodeTermsRoute
  '/$countryCode/virtual-try-on': typeof CountryCodeVirtualTryOnRoute
  '/$countryCode/': typeof CountryCodeIndexRoute
  '/$countryCode/account/addresses': typeof CountryCodeAccountAddressesRoute
  '/$countryCode/account/login': typeof CountryCodeAccountLoginRoute
  '/$countryCode/account/orders': typeof CountryCodeAccountOrdersRoute
  '/$countryCode/account/password-login': typeof CountryCodeAccountPasswordLoginRoute
  '/$countryCode/account/profile': typeof CountryCodeAccountProfileRoute
  '/$countryCode/account/register': typeof CountryCodeAccountRegisterRoute
  '/$countryCode/blogs/$slug': typeof CountryCodeBlogsSlugRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/blogs/': typeof CountryCodeBlogsIndexRoute
  '/$countryCode/account/orders_/$orderId': typeof CountryCodeAccountOrdersOrderIdRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/$countryCode'
    | '/cart'
    | '/checkout'
    | '/health'
    | '/store'
    | '/$countryCode/about'
    | '/$countryCode/account'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/contact'
    | '/$countryCode/faqs'
    | '/$countryCode/phone-verify'
    | '/$countryCode/privacy-policy'
    | '/$countryCode/return-policy'
    | '/$countryCode/search'
    | '/$countryCode/shipping-policy'
    | '/$countryCode/store'
    | '/$countryCode/terms'
    | '/$countryCode/virtual-try-on'
    | '/$countryCode/'
    | '/$countryCode/account/addresses'
    | '/$countryCode/account/login'
    | '/$countryCode/account/orders'
    | '/$countryCode/account/password-login'
    | '/$countryCode/account/profile'
    | '/$countryCode/account/register'
    | '/$countryCode/blogs/$slug'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/blogs/'
    | '/$countryCode/account/orders/$orderId'
    | '/$countryCode/order/$orderId/confirmed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/cart'
    | '/checkout'
    | '/health'
    | '/store'
    | '/$countryCode/about'
    | '/$countryCode/account'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/contact'
    | '/$countryCode/faqs'
    | '/$countryCode/phone-verify'
    | '/$countryCode/privacy-policy'
    | '/$countryCode/return-policy'
    | '/$countryCode/search'
    | '/$countryCode/shipping-policy'
    | '/$countryCode/store'
    | '/$countryCode/terms'
    | '/$countryCode/virtual-try-on'
    | '/$countryCode'
    | '/$countryCode/account/addresses'
    | '/$countryCode/account/login'
    | '/$countryCode/account/orders'
    | '/$countryCode/account/password-login'
    | '/$countryCode/account/profile'
    | '/$countryCode/account/register'
    | '/$countryCode/blogs/$slug'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/blogs'
    | '/$countryCode/account/orders/$orderId'
    | '/$countryCode/order/$orderId/confirmed'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/$countryCode'
    | '/cart'
    | '/checkout'
    | '/health'
    | '/store'
    | '/$countryCode/about'
    | '/$countryCode/account'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/contact'
    | '/$countryCode/faqs'
    | '/$countryCode/phone-verify'
    | '/$countryCode/privacy-policy'
    | '/$countryCode/return-policy'
    | '/$countryCode/search'
    | '/$countryCode/shipping-policy'
    | '/$countryCode/store'
    | '/$countryCode/terms'
    | '/$countryCode/virtual-try-on'
    | '/$countryCode/'
    | '/$countryCode/account/addresses'
    | '/$countryCode/account/login'
    | '/$countryCode/account/orders'
    | '/$countryCode/account/password-login'
    | '/$countryCode/account/profile'
    | '/$countryCode/account/register'
    | '/$countryCode/blogs/$slug'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/blogs/'
    | '/$countryCode/account/orders_/$orderId'
    | '/$countryCode/order/$orderId/confirmed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CountryCodeRoute: typeof CountryCodeRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  HealthRoute: typeof HealthRoute
  StoreRoute: typeof StoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode': {
      id: '/$countryCode'
      path: '/$countryCode'
      fullPath: '/$countryCode'
      preLoaderRoute: typeof CountryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/': {
      id: '/$countryCode/'
      path: '/'
      fullPath: '/$countryCode/'
      preLoaderRoute: typeof CountryCodeIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/virtual-try-on': {
      id: '/$countryCode/virtual-try-on'
      path: '/virtual-try-on'
      fullPath: '/$countryCode/virtual-try-on'
      preLoaderRoute: typeof CountryCodeVirtualTryOnRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/terms': {
      id: '/$countryCode/terms'
      path: '/terms'
      fullPath: '/$countryCode/terms'
      preLoaderRoute: typeof CountryCodeTermsRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/store': {
      id: '/$countryCode/store'
      path: '/store'
      fullPath: '/$countryCode/store'
      preLoaderRoute: typeof CountryCodeStoreRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/shipping-policy': {
      id: '/$countryCode/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/$countryCode/shipping-policy'
      preLoaderRoute: typeof CountryCodeShippingPolicyRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/search': {
      id: '/$countryCode/search'
      path: '/search'
      fullPath: '/$countryCode/search'
      preLoaderRoute: typeof CountryCodeSearchRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/return-policy': {
      id: '/$countryCode/return-policy'
      path: '/return-policy'
      fullPath: '/$countryCode/return-policy'
      preLoaderRoute: typeof CountryCodeReturnPolicyRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/privacy-policy': {
      id: '/$countryCode/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/$countryCode/privacy-policy'
      preLoaderRoute: typeof CountryCodePrivacyPolicyRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/phone-verify': {
      id: '/$countryCode/phone-verify'
      path: '/phone-verify'
      fullPath: '/$countryCode/phone-verify'
      preLoaderRoute: typeof CountryCodePhoneVerifyRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/faqs': {
      id: '/$countryCode/faqs'
      path: '/faqs'
      fullPath: '/$countryCode/faqs'
      preLoaderRoute: typeof CountryCodeFaqsRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/contact': {
      id: '/$countryCode/contact'
      path: '/contact'
      fullPath: '/$countryCode/contact'
      preLoaderRoute: typeof CountryCodeContactRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/checkout': {
      id: '/$countryCode/checkout'
      path: '/checkout'
      fullPath: '/$countryCode/checkout'
      preLoaderRoute: typeof CountryCodeCheckoutRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/cart': {
      id: '/$countryCode/cart'
      path: '/cart'
      fullPath: '/$countryCode/cart'
      preLoaderRoute: typeof CountryCodeCartRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account': {
      id: '/$countryCode/account'
      path: '/account'
      fullPath: '/$countryCode/account'
      preLoaderRoute: typeof CountryCodeAccountRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/about': {
      id: '/$countryCode/about'
      path: '/about'
      fullPath: '/$countryCode/about'
      preLoaderRoute: typeof CountryCodeAboutRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/blogs/': {
      id: '/$countryCode/blogs/'
      path: '/blogs'
      fullPath: '/$countryCode/blogs/'
      preLoaderRoute: typeof CountryCodeBlogsIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/products/$handle': {
      id: '/$countryCode/products/$handle'
      path: '/products/$handle'
      fullPath: '/$countryCode/products/$handle'
      preLoaderRoute: typeof CountryCodeProductsHandleRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/categories/$handle': {
      id: '/$countryCode/categories/$handle'
      path: '/categories/$handle'
      fullPath: '/$countryCode/categories/$handle'
      preLoaderRoute: typeof CountryCodeCategoriesHandleRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/blogs/$slug': {
      id: '/$countryCode/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/$countryCode/blogs/$slug'
      preLoaderRoute: typeof CountryCodeBlogsSlugRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/register': {
      id: '/$countryCode/account/register'
      path: '/register'
      fullPath: '/$countryCode/account/register'
      preLoaderRoute: typeof CountryCodeAccountRegisterRouteImport
      parentRoute: typeof CountryCodeAccountRoute
    }
    '/$countryCode/account/profile': {
      id: '/$countryCode/account/profile'
      path: '/profile'
      fullPath: '/$countryCode/account/profile'
      preLoaderRoute: typeof CountryCodeAccountProfileRouteImport
      parentRoute: typeof CountryCodeAccountRoute
    }
    '/$countryCode/account/password-login': {
      id: '/$countryCode/account/password-login'
      path: '/password-login'
      fullPath: '/$countryCode/account/password-login'
      preLoaderRoute: typeof CountryCodeAccountPasswordLoginRouteImport
      parentRoute: typeof CountryCodeAccountRoute
    }
    '/$countryCode/account/orders': {
      id: '/$countryCode/account/orders'
      path: '/orders'
      fullPath: '/$countryCode/account/orders'
      preLoaderRoute: typeof CountryCodeAccountOrdersRouteImport
      parentRoute: typeof CountryCodeAccountRoute
    }
    '/$countryCode/account/login': {
      id: '/$countryCode/account/login'
      path: '/login'
      fullPath: '/$countryCode/account/login'
      preLoaderRoute: typeof CountryCodeAccountLoginRouteImport
      parentRoute: typeof CountryCodeAccountRoute
    }
    '/$countryCode/account/addresses': {
      id: '/$countryCode/account/addresses'
      path: '/addresses'
      fullPath: '/$countryCode/account/addresses'
      preLoaderRoute: typeof CountryCodeAccountAddressesRouteImport
      parentRoute: typeof CountryCodeAccountRoute
    }
    '/$countryCode/order/$orderId/confirmed': {
      id: '/$countryCode/order/$orderId/confirmed'
      path: '/order/$orderId/confirmed'
      fullPath: '/$countryCode/order/$orderId/confirmed'
      preLoaderRoute: typeof CountryCodeOrderOrderIdConfirmedRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/orders_/$orderId': {
      id: '/$countryCode/account/orders_/$orderId'
      path: '/orders/$orderId'
      fullPath: '/$countryCode/account/orders/$orderId'
      preLoaderRoute: typeof CountryCodeAccountOrdersOrderIdRouteImport
      parentRoute: typeof CountryCodeAccountRoute
    }
  }
}

interface CountryCodeAccountRouteChildren {
  CountryCodeAccountAddressesRoute: typeof CountryCodeAccountAddressesRoute
  CountryCodeAccountLoginRoute: typeof CountryCodeAccountLoginRoute
  CountryCodeAccountOrdersRoute: typeof CountryCodeAccountOrdersRoute
  CountryCodeAccountPasswordLoginRoute: typeof CountryCodeAccountPasswordLoginRoute
  CountryCodeAccountProfileRoute: typeof CountryCodeAccountProfileRoute
  CountryCodeAccountRegisterRoute: typeof CountryCodeAccountRegisterRoute
  CountryCodeAccountOrdersOrderIdRoute: typeof CountryCodeAccountOrdersOrderIdRoute
}

const CountryCodeAccountRouteChildren: CountryCodeAccountRouteChildren = {
  CountryCodeAccountAddressesRoute: CountryCodeAccountAddressesRoute,
  CountryCodeAccountLoginRoute: CountryCodeAccountLoginRoute,
  CountryCodeAccountOrdersRoute: CountryCodeAccountOrdersRoute,
  CountryCodeAccountPasswordLoginRoute: CountryCodeAccountPasswordLoginRoute,
  CountryCodeAccountProfileRoute: CountryCodeAccountProfileRoute,
  CountryCodeAccountRegisterRoute: CountryCodeAccountRegisterRoute,
  CountryCodeAccountOrdersOrderIdRoute: CountryCodeAccountOrdersOrderIdRoute,
}

const CountryCodeAccountRouteWithChildren =
  CountryCodeAccountRoute._addFileChildren(CountryCodeAccountRouteChildren)

interface CountryCodeRouteChildren {
  CountryCodeAboutRoute: typeof CountryCodeAboutRoute
  CountryCodeAccountRoute: typeof CountryCodeAccountRouteWithChildren
  CountryCodeCartRoute: typeof CountryCodeCartRoute
  CountryCodeCheckoutRoute: typeof CountryCodeCheckoutRoute
  CountryCodeContactRoute: typeof CountryCodeContactRoute
  CountryCodeFaqsRoute: typeof CountryCodeFaqsRoute
  CountryCodePhoneVerifyRoute: typeof CountryCodePhoneVerifyRoute
  CountryCodePrivacyPolicyRoute: typeof CountryCodePrivacyPolicyRoute
  CountryCodeReturnPolicyRoute: typeof CountryCodeReturnPolicyRoute
  CountryCodeSearchRoute: typeof CountryCodeSearchRoute
  CountryCodeShippingPolicyRoute: typeof CountryCodeShippingPolicyRoute
  CountryCodeStoreRoute: typeof CountryCodeStoreRoute
  CountryCodeTermsRoute: typeof CountryCodeTermsRoute
  CountryCodeVirtualTryOnRoute: typeof CountryCodeVirtualTryOnRoute
  CountryCodeIndexRoute: typeof CountryCodeIndexRoute
  CountryCodeBlogsSlugRoute: typeof CountryCodeBlogsSlugRoute
  CountryCodeCategoriesHandleRoute: typeof CountryCodeCategoriesHandleRoute
  CountryCodeProductsHandleRoute: typeof CountryCodeProductsHandleRoute
  CountryCodeBlogsIndexRoute: typeof CountryCodeBlogsIndexRoute
  CountryCodeOrderOrderIdConfirmedRoute: typeof CountryCodeOrderOrderIdConfirmedRoute
}

const CountryCodeRouteChildren: CountryCodeRouteChildren = {
  CountryCodeAboutRoute: CountryCodeAboutRoute,
  CountryCodeAccountRoute: CountryCodeAccountRouteWithChildren,
  CountryCodeCartRoute: CountryCodeCartRoute,
  CountryCodeCheckoutRoute: CountryCodeCheckoutRoute,
  CountryCodeContactRoute: CountryCodeContactRoute,
  CountryCodeFaqsRoute: CountryCodeFaqsRoute,
  CountryCodePhoneVerifyRoute: CountryCodePhoneVerifyRoute,
  CountryCodePrivacyPolicyRoute: CountryCodePrivacyPolicyRoute,
  CountryCodeReturnPolicyRoute: CountryCodeReturnPolicyRoute,
  CountryCodeSearchRoute: CountryCodeSearchRoute,
  CountryCodeShippingPolicyRoute: CountryCodeShippingPolicyRoute,
  CountryCodeStoreRoute: CountryCodeStoreRoute,
  CountryCodeTermsRoute: CountryCodeTermsRoute,
  CountryCodeVirtualTryOnRoute: CountryCodeVirtualTryOnRoute,
  CountryCodeIndexRoute: CountryCodeIndexRoute,
  CountryCodeBlogsSlugRoute: CountryCodeBlogsSlugRoute,
  CountryCodeCategoriesHandleRoute: CountryCodeCategoriesHandleRoute,
  CountryCodeProductsHandleRoute: CountryCodeProductsHandleRoute,
  CountryCodeBlogsIndexRoute: CountryCodeBlogsIndexRoute,
  CountryCodeOrderOrderIdConfirmedRoute: CountryCodeOrderOrderIdConfirmedRoute,
}

const CountryCodeRouteWithChildren = CountryCodeRoute._addFileChildren(
  CountryCodeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CountryCodeRoute: CountryCodeRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  HealthRoute: HealthRoute,
  StoreRoute: StoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
